# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title/

# Setup
title:            Guia Xarxes Socials
tagline:          'Generalitat de Catalunya'
description:      'Guia de xarxes socials de la Generalitat de Catalunya'
baseurl:              http://generalitat.github.io/guia/

# Gems
gems:
  - jekyll-sitemap
